-- 두 테이블에서 2022년 10월에 작성된 제목, 게시글 id, 댓글 작성자 id, 댓글내용, 댓글 작성일 조회
-- 댓글작성일 기준 오름차순 -> 게시글 제목 기준 오름차순
SELECT B.TITLE, R.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R
WHERE YEAR(B.CREATED_DATE) = '2022' AND MONTH(B.CREATED_DATE) = '10' AND B.BOARD_ID = R.BOARD_ID
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC